### ISSUE TITLE
Large messages with infrequent restarts result in a jammed Store

### ISSUE THREAD

**Issue by tkurki** [behrad/mqtt-nedb-store#2]
We have a case where we use nedb Store for queuing outgoing rather verbose JSON messages.

If you publish enough data even in a perfectly functioning system (the mqtt server is always reachable) the outgoing nedb store grows so large that nedb fails to reopen it upon system/mqtt client restart and the system can not recover from this condition, even if all the outgoing messages have been sent ok.

**Comment by tkurki** [comment]
Nedb database is compacted by default [only when you load the database](https://github.com/louischatriot/nedb#persistence). However it has a built in timed compaction feature, which would be very easy to activate when receiving options like

```
const myNedbStore = new Manager(path, { outgoing: { autocompactionInterval: 60 } } )
```

Is this something you would consider adding? I can provide the PR.

**Comment by tkurki** [comment]
That should be 60000, not 60...

**Comment by behrad** [comment]
If you have tested this, a PR would be welcome 👍
